### PR TITLE
fix: missing image dentalTab

### PR DESCRIPTION
**Pull request by vanshb03**
Fixed image error @LordFarquaadtheCreator

### CODE REVIEW

**Comment by garvsl** [comment]
goated

**Comment by LordFarquaadtheCreator** [comment]
ayo why tag me i didnt do UI

**Comment by vanshb03** [comment]
@garvsl told me to take a look at it haha, so I had to @ him before anyone haha

**Comment by vanshb03** [comment]
> ayo why tag me i didnt do UI

cuz we were talking about it on disc haha

**Pull request merged**
